# Generated by Django 5.2.7 on 2025-10-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_unidad_descripcion_alter_opcion_texto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL del Video'),
        ),
    ]
