# Generated by Django 5.2.7 on 2025-10-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_unidad_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='tipo_contenido',
            field=models.CharField(choices=[('VIDEO', 'Video (Contenido principal)'), ('FORM', 'Formulario / Cuestionario'), ('TEXT', 'Texto (Contenido de lectura)')], default='TEXT', max_length=5, verbose_name='Tipo de Contenido'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name="URL de Video (Solo si el Tipo es 'VIDEO')"),
        ),
    ]
