# Generated by Django 5.2.7 on 2025-11-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_unidad_tipo_contenido_alter_unidad_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='juego_archivo',
            field=models.FileField(blank=True, null=True, upload_to='juegos/', verbose_name="Archivo del Juego (HTML5 local, solo si el Tipo es 'JUEGO')"),
        ),
        migrations.AddField(
            model_name='unidad',
            name='juego_url',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name="URL del Juego (Solo si el Tipo es 'JUEGO')"),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='tipo_contenido',
            field=models.CharField(choices=[('VIDEO', 'Video (Contenido principal)'), ('FORM', 'Formulario / Cuestionario'), ('TEXT', 'Texto (Contenido de lectura)'), ('JUEGO', 'Juego interactivo')], default='TEXT', max_length=6, verbose_name='Tipo de Contenido'),
        ),
    ]
