# Generated by Django 5.2.7 on 2025-11-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_unidad_juego_archivo_unidad_juego_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidad',
            name='video_url',
        ),
        migrations.AddField(
            model_name='unidad',
            name='video_archivo',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Archivo de video (MP4)'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='juego_archivo',
            field=models.FileField(blank=True, null=True, upload_to='juegos/', verbose_name='Archivo ZIP/HTML del juego (si es JUEGO)'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='juego_url',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='URL del juego externo (si es JUEGO)'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='tipo_contenido',
            field=models.CharField(choices=[('VIDEO', 'Video (Contenido principal)'), ('FORM', 'Formulario / Cuestionario'), ('TEXT', 'Texto (Contenido de lectura)'), ('JUEGO', 'Juego interactivo')], default='TEXT', max_length=5),
        ),
    ]
