# Generated by Django 5.2.7 on 2025-11-06 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_unidad_video_url_unidad_video_archivo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asociacion', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisores', to='app.curso')),
                ('profesor', models.ForeignKey(limit_choices_to={'role': 'profesor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('curso', 'profesor')},
            },
        ),
    ]
