# Generated by Django 5.2.7 on 2025-11-06 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_cursoprofesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='codigo_profesor',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='profesor_asignado',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'profesor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Progreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidades_completadas', models.IntegerField(default=0)),
                ('total_unidades', models.IntegerField(default=0)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='app.curso')),
                ('estudiante', models.ForeignKey(limit_choices_to={'role': 'estudiante'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
