# Generated by Django 5.2.7 on 2025-11-07 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadcompletada',
            name='completado',
            field=models.BooleanField(default=True),
        ),
    ]
