# Generated by Django 5.2.7 on 2025-11-13 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_unidadcompletada_completado'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='contenido_texto',
            field=models.TextField(blank=True, null=True, verbose_name='Contenido textual (si es TEXT)'),
        ),
    ]
