# Generated by Django 5.2.7 on 2025-11-13 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_unidad_contenido_texto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidad',
            name='video_archivo',
        ),
        migrations.AddField(
            model_name='unidad',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
