# Generated by Django 5.2.7 on 2025-11-14 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_unidad_video_archivo_unidad_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.IntegerField(default=1)),
                ('tipo', models.CharField(choices=[('BORDE', 'Borde de foto'), ('ICONO', 'Icono de perfil'), ('FONDO', 'Fondo de perfil')], max_length=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='tienda_items/')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='puntos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='puntos_totales',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.itemtienda')),
            ],
            options={
                'unique_together': {('usuario', 'item')},
            },
        ),
    ]
