# Generated by Django 5.2.7 on 2025-11-17 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_customuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemtienda',
            name='imagen',
        ),
        migrations.AddField(
            model_name='itemtienda',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='tienda_items/'),
        ),
        migrations.AlterField(
            model_name='itemtienda',
            name='tipo',
            field=models.CharField(choices=[('BORDE', 'Borde de foto'), ('ICONO', 'Icono de perfil'), ('FONDO', 'Fondo de perfil'), ('GIF', 'GIF animado')], max_length=20),
        ),
    ]
